version: "3"

services: 
    db:
        image: postgres:13-alpine
        environment:
            POSTGRES_DB: database
            POSTGRES_USER: database
            POSTGRES_PASSWORD: database
        volumes: 
            - "./db-data:/var/lib/postgresql"

    app:
        build: .
        depends_on: 
            - db
        environment: 
            DATABASE_URL: "postgresql://database:database@db:5432/database"
        ports: 
            - "3000:80"
        volumes: 
            - "./app:/app/app"
