version: "3"

services: 
    db:
        image: postgres:13-alpine
        environment:
            POSTGRES_DB: database
            POSTGRES_USER: database
            POSTGRES_PASSWORD: database


    app:
        build: .
        depends_on: 
            - db
        environment: 
            DATABASE_URL: "postgresql://database:database@db:5432/database"
        ports: 
            - "3000:80"
        volumes: 
            - "./app:/app/app"

    pg-admin:
        profiles: ["pg-admin"]
        image: dpage/pgadmin4
        ports:
            - "1212:80"
        environment:
            PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
            PGADMIN_DEFAULT_PASSWORD: "123456"
        